### ISSUE TITLE
SLURM `task_defaults` overrides `slurmfile.yaml`

### ISSUE THREAD

**Issue by Dooruk** [GEOS-ESM/swell#382]
SLURM hierarchy issue, thanks @rtodling for noticing

**Comment by rtodling** [comment]
FYI: commenting out the line you suggest here:

https://github.com/GEOS-ESM/swell/blob/9fcbb8186f7df797e23f8da3e1900b61fd987bab/src/swell/utilities/slurm.py#L46

does work; so the matter is to have these defaults set before the overwrite by the user-specified --slurm option is passed in the create.

**Comment by ashiklom** [comment]
Can you post the `slurmfile.yaml` causing this behavior?

Note that the current behavior is that task-specific values always override task-agnostic values, even if the latter is passed through the user-specified slurmfile. 

This is by design. But the designed order of inheritance can be changed if we don't like it.

To override task-specific defaults, you need to put task-specific overrides into the slurmfile. E.g., Something like:

```yaml
slurm_defaults_global:
  nodes: 1   # <-- This will be overridden by task-specific defaults
slurm_directives_tasks:
  RunJediVariationalExecutable:
    all:
      nodes: 4   # <-- This has higher priority than task-specific defaults
    geos_atmosphere:
      nodes: 5   # <-- This has the highest priority.
```

If that's what you have and the values are still wrong, then that's indeed a bug!

**Comment by Dooruk** [comment]
> Can you post the `slurmfile.yaml` causing this behavior?

```yaml
# Ricardo's slurmfile.yaml
 
slurm_directives_tasks:
  RunJediVariationalExecutable:
    geos_atmosphere:
      nodes: 7
      ntasks-per-node: 36
```

Now that I think about it again, mine below works:

```yaml
# Doruk's slurmfile.yaml
 
# Task-specific settings. These always override the globals (above) and any
# hard-coded values.
slurm_directives_tasks:
  RunJediVariationalExecutable:
    geos_ocean:
      nodes: 20
      ntasks-per-node: 40

```

So I suspect @rtodling's issue might be different. I will give it a try on my end with his file directly.
