### ISSUE TITLE
(SE) Optional tasks in Cylc suite do not trigger keys to be added to `experiment.yaml`

### ISSUE THREAD

**Issue by Dooruk** [GEOS-ESM/swell#440]
The issue arises when a key in `task_questions.yaml` or `suite_questions.yaml` needs to be used by a conditional task in `flow.cylc`, example below.

Following is the entry in my `task_questions.yaml`. I don't see `cice6_domains` in my `experiment.yaml` after `swell create` step:

```yaml
cice6_domains:
  ask_question: true
  default_value: defer_to_model
  models:
  - geos_marine
  options: defer_to_model
  prompt: Which CICE6 domains do you wish to run DA for?
  tasks:
  - RunJediConvertStateSoca2ciceExecutable
  type: string-check-list
```

Because only the `RunJediConvertStateSoca2ciceExecutable` task requires this. In `flow.cylc`, this task is used only when `cice6` is active:

```cylc
    {% if 'cice6' in marine_models %}

    [[RunJediConvertStateSoca2ciceExecutable-{{model_component}}]]
        script = "swell task RunJediConvertStateSoca2ciceExecutable $config -d $datetime -m {{model_component}}"
        platform = {{platform}}
        execution time limit = {{scheduling["RunJediConvertStateSoca2ciceExecutable"]["execution_time_limit"]}}
        [[[directives]]]
        {%- for key, value in scheduling["RunJediConvertStateSoca2ciceExecutable"]["directives"][model_component].items() %}
            --{{key}} = {{value}}
        {%- endfor %}

    {% endif %}
```

While creating `experiment.yaml`, Swell scans `flow.cylc` `[runtime]` section to find unique tasks and hence to define associated `questions (keys)` in `task_questions.yaml`. `marine_models` was not defined during this non-exhaustive search step, hence this task inside the conditional is essentially not registered. I'm talking about at this stage of the code:

https://github.com/GEOS-ESM/swell/blob/597bbbe9c87867178a130a10c6d07418d1a212d8/src/swell/deployment/prepare_config_and_suite/prepare_config_and_suite.py#L382

Here, `self.experiment_dict` contains `model_components` so tasks inside those conditionals work:

```cylc
    {% for model_component in model_components %}

    [[LinkGeosOutput-{{model_component}}]]
        script = "swell task LinkGeosOutput $config -d $datetime -m {{model_component}}"
    {% endfor %}
```

Anyways, this was really long explanation but happy to explain even further, I had to do some low-level digging to find this issue.

_Originally posted by @Dooruk in https://github.com/GEOS-ESM/swell/issues/419#issuecomment-2405472031_
