### ISSUE TITLE
Alternative handling of anchor variables

### ISSUE THREAD

**Issue by rtodling** [GEOS-ESM/swell#558]
This  is to lay out two issues related to the way things work in SWELL that would more nicely work differently.  

1. Recently, I needed to make a change to one of the yaml files related to the atmosphere analysis. Basically, added something like this to background.yaml

file io names: &file_io_names
  eastward_wind: ua
  long_list_of_var_defs_here ...

This background file, simply defines the var name **file_io_names** - it doesn't use it.  I then edited yaml files, eg. varincrement1.yaml  and added

file io name: *file_io_names

notice this file, varincrement1.yaml does not define the anchor, it was supposed to simply used it. 

Unfortunately, SWELL crates w/ an error complaining that file_io)names is not defined. The issue is that the machinery that replaces the variable name by the actual entries only works when the achor is defined in that peanut yaml file - it's not enough to have it defined once in the beginning.

2. This to me unveil an even more fundamental issue. The problem above would be not be an issue if SWELL let the anchors as such - meaning if it never attempted to replace, say, file_io_names w/ it details.

SOLUTION: What I would like to see if for SWELL to leave the answer all *var_name untouched. So that the final yaml provided to the application will have the definition of the anchor and the *var_name in the final file.

**Comment by mathomp4** [comment]
Swell could use ruamel.yaml to preserve anchors in output. For example:
```python
from ruamel.yaml import YAML
import yaml
from io import StringIO

yaml_str = """
var: &save This long string
var2: *save
"""

# ruamel.yaml preserves anchors
ruamel_yaml = YAML()
data_ruamel = ruamel_yaml.load(StringIO(yaml_str))
output_ruamel = StringIO()
ruamel_yaml.dump(data_ruamel, output_ruamel)

# PyYAML does not preserve anchors
data_pyyaml = yaml.safe_load(yaml_str)
output_pyyaml = yaml.dump(data_pyyaml, default_flow_style=False)

# Display both outputs
print("ruamel.yaml output (anchors preserved):")
print(output_ruamel.getvalue())

print("\nPyYAML output (anchors expanded):")
print(output_pyyaml)
```
The output of this is:
```
❯ python3 test_combined.py
ruamel.yaml output (anchors preserved):
var: &save This long string
var2: *save


PyYAML output (anchors expanded):
var: This long string
var2: This long string
```

**Comment by ashiklom** [comment]
I support switching to ruamel! It seems like the most painless solution. (We just have to keep an eye on some potential issues with pypi coming in the future --- https://pypi.org/project/ruamel.yaml/ --- but this package is popular enough that I'm sure there will be a solid workaround).

**Comment by mranst** [comment]
I think there's an additional issue here. I'm not super familiar with ruamel, but my impression is that any YAML interpreter won't be able to handle using anchor variables in a stream where they are not defined (like in Ricardo's example with defining `&file io names` in `background.yaml`, then trying to use them in `varincrement.yaml`). I tried this with ruamel, and it still fails.

I could be mistaken, but I think this would necessitate re-structuring the way that JEDI configuration YAML's are handled by Swell. The way it works now (I believe) is that each YAML is read into a dictionary individually, so anchor variables need to be defined in each file in which they are used. I'm not sure what the ideal solution to this would be. It seems like this might be able to be done with jinja templating, or maybe even combining multiple YAML files into a single string before interpretation, but both seem very fragile and dependent on the order in which files are specified

**Comment by ashiklom** [comment]
Ah, I missed that -- thanks for the clarification, Michael! Anchors across files are a much more complicated issue.

Strictly speaking, **YAML is not supposed to allow you to do this at all**. The YAML spec clearly states that every [YAML document should be completely independent](https://yaml.org/spec/1.2.2/#chapter-9-document-stream-productions), with no external dependencies. Anchors across files violate this core specification. Moreover, inheriting anchors from other files without any explicit indication of where they came from also makes it _really_ hard to reason about YAML files in the swell source code (i.e., at a minimum, you would need to search Swell source code for `&file_io_names`...but then what if it's defined differently in multiple places?).

A few suggestions:

# Option 1: Replace YAML with Python (My strong preference!)

What I would really recommend here is (as I've said before), for hard-coded _internal_ package data, we replace YAML with just Python. Here's a quick example for this use case:

Original:

```yaml
# background_ensemble.yaml
date: '{{window_begin_iso}}'
members from template:
  template:
    datetime: '{{local_background_time_iso}}'
    filetype: cube sphere history
    provider: geos
    datapath: '.'
    filenames: ['ebkg/mem%mem%/geos.mem%mem%.%yyyy%mm%dd_%hh%MM%ssz.nc4',
                'fv3-jedi/bkg/geos.crtmsrf.{{horizontal_resolution}}.nc4']
    state variables: &statevars
    - eastward_wind
    - northward_wind
    - air_temperature
    - air_pressure_thickness
    - air_pressure_at_surface
# ...
    field io names: &field_io_names
      eastward_wind: ua
      northward_wind: va
      air_temperature: t
      air_pressure_thickness: delp
      water_vapor_mixing_ratio_wrt_moist_air: q
# ...
  pattern: '%mem%'
  nmembers: {{ensemble_num_members}}
  zero padding: 3

#####
# analysis.yaml
filetype: cube sphere history
provider: geos
datapath: '{{cycle_dir}}'
filename: '{{experiment_id}}.analysis.%yyyy%mm%dd_%hh%MM%ssz.nc4'
first: PT0H
frequency: PT1H
#field io names: *field_io_names
field io names:
  eastward_wind: ua
  northward_wind: va
  air_temperature: t
  air_pressure_thickness: delp
# ...
```

Python approach:

```python
# swell/configuration/jedi/interfaces/geos_atmosphere/model/background_ensemble.py
state_variables = [
    "eastward_wind",
    "northward_wind",
    "air_temperature",
    "air_pressure_thickness",
    # ...
]

field_io_names = {
    "eastward_wind": "ua",
    "northward_wind": "va",
    "air_temperature": "t",
    "air_pressure_thickness": "delp",
    # ...
}

background_ensemble = {
    "date": config.window_begin_iso,
    "members from template": {
        "template": {
            "datetime": config.local_background_time_iso,
            "filetype": "cube sphere history",
            "provider": "geos",
            "datapath": ".",
            "filenames": ['ebkg/mem%mem%/geos.mem%mem%.%yyyy%mm%dd_%hh%MM%ssz.nc4',
                          'fv3-jedi/bkg/geos.crtmsrf.{{horizontal_resolution}}.nc4'],
            "state variables": state_variables,
            "field io names": field_io_names
        }
    }
}

########################################
# swell/configuration/jedi/interfaces/geos_atmosphere/model/analysis.py
from swell.configuration.jedi.interfaces.geos_atmosphere.model import (
    state_variables,
    field_io_names
)

analysis = {
    "filetype": "cube sphere history",
    "provider": "geos",
    "datapath": config.cycle_dir,
    "filename": f"{config.experiment_id}.analysis.%yyyy%mm%dd_%hh%MM%ssz.nc4",
    "first": "PT0H",
    "frequency": "PT1H",
    # Here, start with field_io_names but update as needed
    "field io names": field_io_names | {
        "new_variable": "someunit",
        # NOTE: We can even modify existing definitions.
        # Bad example here -- ua is common -- but you get the idea...
        "eastward_wind": "u_east"
    }
}
```

In the python version, it's immediately obvious that the `analysis` config is pulling its data from `background_experiment`. It's also straightforward to add new, or even update existing, data in `field_io_names`. Finally, you eliminate the ugly and often confusing Jinja templating (`{{cycle_dir}}`) and just replace it directly with Python objects.

# Option 2: Don't parse YAML at all

If all we want to do is read these YAMLs, apply some Jinja templating, and then writing them back out _without doing **anything** with the internal YAML data_ (and, critically, without even checking that they are valid YAML), then we could just do that.

```python
with open("background_ensemble.yaml", "r") as f:
    template = f.read()
vars = {
    "window_begin_iso": config.window_begin_iso,
    "local_background_time_iso": config.local_background_time_iso,
    "horizontal_resolution": config.horizontal_resolution
}
result = template_string_jinja2(logger, template, vars)
```

Note that in this approach, the `template` object is basically unusable inside of Python itself. But if all Swell is doing is populating YAML files for JEDI, and we're OK deferring to JEDI (or whatever else) to concatenate the YAML, this works fine.

# Option 3: Custom `#!use`/`#!includes` YAML syntax (or something)

This is by far my least favorite because it requires more work than Option 1 (Python) and introduces a new custom YAML syntax on top of the already somewhat weird YAML template syntax. The basic idea is something like this:


```yaml
# file1.yaml
# ---------
variable: &var
 - a
 - b
 - c

############
# file2.yaml
# ---------
#!include ./file1.yaml
somevar: *var
```

When we read `file2.yaml`, we first replace the `#!include file1.yaml` with the literal contents of `file1.yaml` as a string, and then parse the entire concatenated string as a YAML.

-----

@rtodling @metdyn What do you think?
