### ISSUE TITLE
YAML Configuration | Radiosondes

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#78]
## Agreement with GSI using GeoVaLs in UFO (Hofx)

- [ ] Done

## Agreement with GSI using GeoVaLs in UFO (Quality control)

- [ ] Done

## Agreement with GSI using Swell

- [ ] Done

## Current issues:

- [ ] https://github.com/JCSDA-internal/ufo/pull/2218

**Comment by gmao-msienkie** [comment]
Original yaml file fails to be processed -  the input data is missing 'LaunchTime' values.  If a station has more than one launch in a synoptic time, the launch time would be used to group the obs from each launch separately.  In the GSI the obs error inflation when multiple obs exist inside vertical model layers is done report-by-report, hence, sounding by sounding.  Without launch time the multiple launches from a station would be grouped together for that filter.

**Comment by danholdaway** [comment]
![sondes_gsihofxbc_vs_hofx_air_temperature](https://user-images.githubusercontent.com/27729500/190192023-ff96587e-89b5-4568-9275-edac52d2097a.png)
![sondes_gsihofxbc_vs_hofx_eastward_wind](https://user-images.githubusercontent.com/27729500/190192025-43d654b8-d47e-4125-be62-165cf4fb4194.png)
![sondes_gsihofxbc_vs_hofx_northward_wind](https://user-images.githubusercontent.com/27729500/190192028-690d5558-5896-4034-8d40-37f04b3e38c4.png)
![sondes_gsihofxbc_vs_hofx_specific_humidity](https://user-images.githubusercontent.com/27729500/190192029-47392bfc-2d28-4f93-a599-34e1bca94a45.png)
![sondes_gsihofxbc_vs_hofx_surface_pressure](https://user-images.githubusercontent.com/27729500/190192032-ae0c9d7a-93b6-4ed8-ae27-472eaba36641.png)
![sondes_gsihofxbc_vs_hofx_virtual_temperature](https://user-images.githubusercontent.com/27729500/190192036-fb10680b-c461-4a24-8b76-2f851fb5091a.png)

**Comment by gmao-jjin3** [comment]
![corscat_eferr_vs_finaler](https://user-images.githubusercontent.com/61251050/199291521-baa848cd-fe6a-4138-aeaf-6dbb2a1d44e9.png)
Observational errors in JEDI and GSI. There is no duplication inflation in JEDI yet.  A question, how to re-set observational error range [100-300 Pa] after the *ObsErrorFactorSfcPressure@ObsFunction* function?   The following *bounds check* filters after it have no impact.  [cory.r.martin@noaa.gov](mailto:cory.r.martin@noaa.gov)
```
  # error inflation based on Ps correction
  - filter: Perform Action
    filter variables:
    - name: surface_pressure
    action:
      name: inflate error
      inflation variable:
        name: ObsErrorFactorSfcPressure@ObsFunction
        options:
          geovar_geomz: geopotential_height
          geovar_sfc_geomz: surface_geopotential_height
  # ObsError >= 100
  - filter: Bounds Check
    filter variables:
    - name: surface_pressure@ObsErrorData
    where:
    - variable: surface_pressure@ObsErrorData
      maxvalue: 100
    action:
      name: assign error
      error parameter: 100
  # ObsError <= 300
  - filter: Bounds Check
    filter variables:
    - name: surface_pressure@ObsErrorData
    where:
    - variable: surface_pressure@ObsErrorData
      minvalue: 300
    action:
      name: assign error
      error parameter: 300

```

**Comment by gmao-jjin3** [comment]
I tried another way to re-set the obs error range:
```
  # ObsError >= 100
  - filter: Variable Assignment
    where:
    - variable:
        #name: surface_pressure@ObsError
        name: ObsErrorData/surface_pressure
      maxvalue: 100
    assignments:
    #- name: surface_pressure@ObsError
    - name: ObsErrorData/surface_pressure
      value: 100
  # ObsError <= 300
  - filter: Variable Assignment
    where:
    - variable:
        #name: surface_pressure@ObsError
        name: ObsErrorData/surface_pressure
      minvalue: 300
    assignments:
    #- name: surface_pressure@ObsError
    - name: ObsErrorData/surface_pressure
      value: 300
```
However, JEDI this time thinks "ObsErrorData" is a new variable and asks an input of data  'type'. However, the UFO document says it is the updated obs error:
https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/jedi-components/ufo/qcfilters/introduction.html#observation-errors

Anyway, Here are steps to handle a surface pressure error in GSI:
1, Assign an initial error (from the error table)
2, ObsErrorFactorSfcPressure@ObsFunction
3, Reset ObsError between Min ~ Max
4, Gross error check:  (O-F)/ObsError
5, Inflate the error, which is the value before Step 3, because of duplication, and make it the final obs error.
